-- Seed inventory items for "Material y Equipo" category (id=2)
-- Data sourced from current physical inventory spreadsheet

INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at) VALUES
-- Time-based equipment usage
(2, 'MONITOR CARDIACO', 'USO MONITOR CARDIACO (1 HORA)', 250.00, 250.00, 0, 0, 'TIME_BASED', 'HOURS', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'BOMBA DE INFUSION', 'USO DE BOMBA DE INFUSION (1 HORA)', 250.00, 250.00, 0, 0, 'TIME_BASED', 'HOURS', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'OXIGENO', 'USO OXIGENO (10 MINUTOS)', 117.00, 16.20, 0, 0, 'TIME_BASED', 'MINUTES', 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Flat-priced equipment and services
(2, 'EKG', 'EKG', 265.00, 265.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'USO DE DESFIBRILADOR', 'USO DE DESFIBRILADOR', 3000.00, 0.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'USO DE GLUCOMETRO', 'USO DE GLUCOMETRO', 49.98, 12.09, 50, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Syringes
(2, 'JERINGAS DESCARTABLES 3 CC', 'JERINGAS DESCARTABLES 3 CC 21 G', 2.25, 0.56, 83, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'JERINGAS DESCARTABLES DE 5 CC', 'JERINGAS DESCARTABLES DE 5 CC 21 G', 2.35, 0.58, 62, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'JERINGAS DESCARTABLES 10 CC', 'JERINGAS DESCARTABLES 10 CC 21 G', 3.60, 0.90, 72, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'JERINGA DE INSULINA DE 1 CC', 'JERINGA DE INSULINA DE 1 CC', 3.40, 0.85, 97, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Aspiration probes
(2, 'SONDA DE ASPIRACION NO. 12', 'SONDA DE ASPIRACION NO. 12 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SONDA DE ASPIRACION NO. 14', 'SONDA DE ASPIRACION NO. 14 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SONDA DE ASPIRACION NO. 16', 'SONDA DE ASPIRACION NO. 16 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SONDA DE ASPIRACION NO. 18', 'SONDA DE ASPIRACION NO. 18 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- IV catheters
(2, 'CATETER INTRAVENOSO NO. 18', 'CATETER INTRAVENOSO NO. 18 (ANGIOCATH) NIPRO', 17.00, 4.25, 29, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'CATETER INTRAVENOSO NO. 20', 'CATETER INTRAVENOSO NO. 20 (ANGIOCATH) NIPRO', 17.00, 4.25, 18, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'CATETER INTRAVENOSO NO. 22', 'CATETER INTRAVENOSO NO. 22 (ANGIOCATH) NIPRO', 17.00, 4.50, 25, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'CATETER INTRAVENOSO NO. 24', 'CATETER INTRAVENOSO NO. 24 (ANGIOCATH) NIPRO', 17.00, 4.50, 22, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- IV supplies
(2, 'SELLOS DE HEPARINA', 'SELLOS DE HEPARINA - TAPON IN LUER-LOK BARAUN', 7.20, 1.80, 17, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'VENOSETH', 'VENOSETH (EQUIPO DE SUERO) PARKINGTON', 10.40, 2.60, 4, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Endotracheal tubes
(2, 'TUBOS ENDOTRAQUEALES #7', 'TUBOS ENDOTRAQUEALES #7, OPERSON', 45.00, 11.25, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'TUBOS ENDOTRAQUEALES #7.5', 'TUBOS ENDOTRAQUEALES #7.5, OPERSON', 45.00, 11.25, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'TUBOS ENDOTRAQUEALES NO. 8', 'TUBOS ENDOTRAQUEALES NO. 8', 88.00, 22.00, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Sutures
(2, 'SUTURAS NYLON # 2-0, 75 CM', 'SUTURAS NYLON # 2-0, 75 CM, ATRAMAT', 39.60, 9.99, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SUTURAS NYLON # 3-0, 75 CM', 'SUTURAS NYLON # 3-0, 75 CM, CE-24 ATRAMAT', 39.60, 9.90, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SUTURAS PGA # 2-0, 75 CM', 'SUTURAS # 3-0, 75 CM, G-37 AHUSADA, ATRAMAT', 63.12, 15.78, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SUTURAS CATGUT SIMPLE # 2-0, 75 CM', 'SUTURAS CATGUT SIMPLE # 2-0, 75 CM, G-37 GRUESA ATRAMAT', 59.00, 14.75, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SUTURAS SEDA # 2-0, 75 CM', 'SUTURAS SEDA # 2-0, 75 CM, SR-26, ATRAMAT', 39.00, 9.75, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Respiratory supplies
(2, 'CANULAS DE OXIGENO BINASAL GRANDE', 'CANULAS DE OXIGENO BINASAL GRANDE, OPERSON', 19.60, 4.90, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'MASCARILLA P/NEBULIZAR ADULTO L', 'MASCARILLA P/NEBULIZAR ADULTO L, OPERSON', 54.00, 13.50, 11, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'MASCARILLA CON RESERVORIO', 'MASCARILLA CON RESERVORIO', 280.00, 70.00, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- PPE and masks
(2, 'MASCARILLAS 3 PLIEGOS', 'MASCARILLAS 3 PLIEGOS ELASTICAS AMBIDEM', 1.46, 0.36, 50, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Gloves
(2, 'GUANTES QUIRURGICOS NO. 6', 'GUANTES QUIRURGICOS NO. 6, AMBIDERM', 11.40, 2.85, 50, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'GUANTES QUIRURGICOS NO. 7', 'GUANTES QUIRURGICOS NO. 7, AMBIDERM', 11.40, 2.85, 49, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'GUANTES DESCARTABLES TALLA S', 'GUANTES DESCARTABLES TALLA S, PROTECT', 3.40, 0.85, 64, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'GUANTES DESCARTABLES TALLA L', 'GUANTES DESCARTABLES TALLA L, PROTECT', 3.40, 0.85, 47, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Foley catheters
(2, 'SONDA FOLEY NO. 14', 'SONDA FOLEY NO. 14, BALON 5-15 ML 2 VIAS, OPERSON', 30.00, 7.50, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SONDA FOLEY NO. 16', 'SONDA FOLEY NO. 16, BALON 5-15 ML 2 VIAS, OPERSON', 30.00, 7.50, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Nasogastric probe
(2, 'SONDA NASOGASTRICA NO. 5', 'SONDA NASOGASTRICA NO. 5', 7.05, 2.35, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Urine collection bags
(2, 'BOLSA RECOLECTORA DE ORINA PIERNA', 'BOLSA RECOLECTORA DE ORINA PIERNA 750 ML, OPERSON', 22.20, 5.55, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'BOLSA RECOLECTORA DE ORINA CAMA', 'BOLSA RECOLECTORA DE ORINA CAMA 2000ML, PARKINGTON', 20.00, 5.00, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- General supplies
(2, 'BAJALENGUAS DE MADERA', 'BAJALENGUAS DE MADERA', 0.54, 0.13, 196, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SONIGEL TUBO 125 GRAMOS', 'SONIGEL TUBO 125 GRAMOS DIQUIVA', 47.00, 11.75, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Needles
(2, 'AGUJA HIPODERMICA NO. 23 G', 'AGUJA HIPODERMICA NO. 23 G', 4.00, 1.00, 196, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'AGUJA 18X1', 'AGUJA 18X1', 1.40, 0.35, 100, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Wound care and dressings
(2, 'GASAS ESTERILES', 'GASAS ESTERILES (UNIDAD)', 3.68, 0.92, 42, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'CURITAS CIRCULARES', 'CURITAS CIRCULARES', 0.56, 0.14, 127, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'VENDA GASA 3X10 Y', 'ROLLO DE VENDA GASA 3 X 10 Y.', 23.28, 5.82, 3, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'TEGADERM 3M', 'TEGADERM 3M, NEXCARE', 91.00, 22.75, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'CAMPO ESTERIL', 'CAMPO ESTERIL', 64.00, 16.00, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Electrodes and tapes
(2, 'ELECTRODOS', 'ELECTRODOS EKG', 4.74, 1.58, 37, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'MICROPORE', 'MICROPORE', 15.50, 15.50, 2, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'MICROPORE DE 1 PULGADA', 'MICROPORE DE 1 PULGADA', 34.00, 8.50, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'ESPARADRAPO', 'ESPARADRAPO', 19.60, 4.90, 0, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Cleaning and hygiene
(2, 'ALCOHOL EN GEL 60 G', 'ALCOHOL EN GEL 60 G', 12.65, 12.65, 1, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SOLUCION DE CLORHEXIDINA 5%', 'GALON SOLUCION DE CLORHEXIDINA 5%', 300.00, 300.00, 1, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'KIT DE HIGIENE', 'KIT DE HIGIENE', 125.00, 56.00, 4, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '1 TORUNDA DE ALGODON', '1 TORUNDA DE ALGODON', 2.00, 0.20, 60, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '10 CC ALCOHOL', 'ALCOHOL', 1.00, 0.20, 198, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
