-- Seed inventory items for "Medicamentos" category (id=1)
-- Data sourced from current physical inventory spreadsheet

INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at) VALUES
-- Antipsychotics
(1, 'TABLETA DE QUTIAPINA (QUETIOXAL 300 MG)', 'TABLETA DE QUETIOXAL 300 MG', 47.50, 15.83, 25, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE OLANZAPINA (ZYPREXA IM 10 MG)', 'AMPOLLA DE OLANZAPINA (ZYPREXA IM 10 MG)', 525.00, 175.00, 12, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'CAJA DE OLANZAPINA (ZYPREXA 5 MG X 14 TABLETAS)', 'CAJA DE ZYPREXA 5 MG X 14 TABLETAS', 1907.80, 635.96, 3, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL OLANZAPINA (ZYPREXA 5 MG)', 'TABLETA INDIVIDUAL OLANZAPINA (ZYPREXA 5 MG)', 136.27, 45.43, 9, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA DE SEROQUEL (QUETIAPINA 100 MG)', 'TABLETA DE SEROQUEL (QUETIAPINA 100 MG)', 72.03, 24.01, 30, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL ROYALINE 5 MG', 'TABLETA INDIVIDUAL ROYALINE TABLETAS 5 MG ROYALINE 5 MG', 7.56, 2.52, 16, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'CAJA DE ARIPIPRAZOL (PRI PAX 5 MG X 30 COMPRIMIDOS)', 'CAJA DE ARIPIPRAZOL (PRI PAX 5 MG X 30 COMPRIMIDOS)', 485.76, 161.92, 1, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, '1 FRASCO DE ARIPIPRAZOL DE 150 ML', '1 FRASCO DE ARIPIPRAZOL DE 150 ML', 819.00, 273.00, 0, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Benzodiazepines and sedatives
(1, 'AMPOLLA MIDAZOLAM (DORMICUM 15MG/3ML)', 'AMPOLLA MIDAZOLAM (DORMICUM 15MG/3ML)', 196.47, 65.49, 14, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL MIDAZOLAM DORMICUM 15 MG', 'TABLETA INDIVIDUAL MIDAZOLAM DORMICUM 15 MG', 22.29, 7.43, 30, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'CAJA MIDAZOLAM (DORMICUM 15 MG X 30 TABLETAS)', 'CAJA MIDAZOLAM (DORMICUM 15 MG X 30 TABLETAS)', 668.31, 222.77, 1, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG)', 'TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG)', 17.32, 4.33, 28, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG) II', 'TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG)', 12.99, 4.33, 27, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE DIAZEPAM DORMICUM 10 MG', 'AMPOLLA DE DIAZEPAM DORMICUM 10 MG', 10.62, 3.54, 2, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL BIPERIDENO HC (BIPARK 2 MG)', 'TABLETA INDIVIDUAL BIPERIDENO HC (BIPARK 2 MG)', 13.50, 4.50, 45, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Pregabalin
(1, 'TABLETA PREGABALINA (MARTESIA 75 MG)', 'TABLETA PREGABALINA (MARTESIA 75 MG)', 46.48, 11.62, 18, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA PREGABALINA (ASTIK 75 MG)', 'TABLETA PREGABALINA (ASTIK 75 MG)', 29.49, 9.83, 4, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Antidepressants (SSRIs)
(1, 'TABLETA INDIVIDUAL DE SEROLUX (SERTRALINA 50 MG)', 'TABLETA INDIVIDUAL DE SEROLUX (SERTRALINA 50 MG)', 37.78, 12.59, 25, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL ALTRULINE (SERTRALINA) 50 MG', 'TABLETA INDIVIDUAL ALTRULINE (SERTRALINA) 50 MG', 87.78, 29.26, 27, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- IV solutions
(1, 'SOLUCION SALINA DE 100 ML', 'SOLUCION SALINA 100 ML', 30.00, 10.00, 18, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'SOLUCION SALINA DE 250 ML', 'SOLUCION SALINA DE 250 ML', 24.84, 8.28, 11, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'SOLUCION SALINA DE 500 ML', 'SOLUCION SALINA DE 500 ML', 28.98, 9.66, 0, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'SOLUCION MIXTA DE 500 ML', 'SOLUCION MIXTA DE 500 ML', 43.20, 14.40, 1, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'SOLUCION HARTMAN 1000 ML', 'SOLUCION HARTMAN 1000 ML', 48.00, 16.00, 4, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'SOLUCION DEXTROSA AL 5% 500 ML', 'SOLUCION DEXTROSA AL 5% 500 ML', 33.60, 11.20, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AGUA ESTERIL PARA INYECCION 100 ML', 'AGUA ESTERIL PARA INYECCION 100 ML', 33.60, 11.20, 2, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AGUA ESTERIL INYECTABLE 500 ML', 'AGUA ESTERIL INYECTABLE 500 ML', 78.00, 26.00, 1, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Anesthetics
(1, 'LIDOCAINA CON EPINEFRINA 10 ML', 'LIDOCAINA CON EPINEFRINA 10 ML', 27.00, 9.00, 4, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA PROPOFOL-LIPURO 1%', 'AMPOLLA PROPOFOL-LIPURO 1%', 81.00, 27.00, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Corticosteroids
(1, 'TABLETA INDIVIDUAL DEXAMETASONA 0.5 MG', 'DEXAMETASONA 0.5 MG', 5.44, 1.36, 36, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'DEXAMETASONA, AMPOLLA 8 MG/2 ML', 'DEXAMETASONA, AMPOLLA 8 MG/2 ML', 126.45, 42.15, 1, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'DEXAMETASONA AMPOLLA 4MG', 'DEXAMETASONA AMPOLLA 4MG', 75.81, 25.27, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Antihistamines and topicals
(1, 'CALADRYL CLEAR LOCION 100 ML', 'CALADRYL CLEAR LOCION 100 ML', 246.21, 82.07, 0, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL DE CLORHIDRATO DE DIFENHIDRAMINA 25 MG', 'TABLETA INDIVIDUAL DE CLORHIDRATO DE DIFENHIDRAMINA 25 MG', 8.31, 2.77, 5, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'HISTAPRIN AMPOLLA 10 MG', 'HISTAPRIN AMPOLLA 10 MG', 130.53, 43.51, 1, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Analgesics and anti-inflammatories
(1, 'TABLETA INDIVIDUAL DE DICLOFENACO 50 MG', 'TABLETA INDIVIDUAL DE DICLOFENACO 50 MG', 3.60, 1.20, 7, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'TABLETA INDIVIDUAL DE ACETAMINOFEN 50 MG', 'TABLETA INDIVIDUAL DE ACETAMINOFEN 50 MG', 2.10, 0.70, 8, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Electrolytes and emergency medications
(1, 'AMPOLLA CLORURO DE POTASIO 5 ML (200 MG/ML)', 'AMPOLLA DE CLORURO DE POTASIO 5 ML (200 MG/ML)', 11.40, 3.80, 1, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE CLORURO DE POTASIO 20MEQ/10 ML', 'AMPOLLA DE CLORURO DE POTASIO 20 MEQ/10 ML', 10.50, 3.50, 25, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE CLORURO DE SODIO 20% (200MG/10ML)', 'AMPOLLA DE CLORURO DE SODIO 20% (200MG/10ML)', 12.00, 4.00, 14, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE BICARBONATO DE SODIO 7%', 'AMPOLLA DE BICARBONATO DE SODIO 7%', 76.50, 25.50, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE SULFATO DE MAGNESIO 50%', 'AMPOLLA DE SULFATO DE MAGNESIO 50%', 14.40, 4.80, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE AMINOFILINA 250MG/5ML', 'AMPOLLA DE AMINOFILINA 250MG/5ML', 15.60, 5.20, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE SULFATO DE ATROPINA 0.5MG/1ML', 'AMPOLLA DE SULFATO DE ATROPINA 0.5MG/1ML', 11.40, 3.80, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE EPINEFRINA 1 MG/1 ML (ADRENALINA)', 'AMPOLLA DE EPINEFRINA 1 MG/1 ML (ADRENALINA)', 11.70, 3.90, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE NALOXONA 0.4MG/1ML', 'AMPOLLA DE NALOXONA 0.4MG/1ML', 35.25, 11.75, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE FUROSEMIDA 20MG/2ML', 'AMPOLLA DE FUROSEMIDA 20MG/2ML', 7.50, 2.50, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE FLUMAZENIL 0.1MG/ML', 'AMPOLLA DE FLUMAZENIL 0.1MG/ML', 390.00, 130.00, 2, 1, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'AMPOLLA DE INOTROPISA 5 ML (DOPAMINA)', 'AMPOLLA DE INOTROPISA 5 ML (DOPAMINA)', 255.00, 85.00, 5, 2, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- GI
(1, '1 SOBRE DE CONTUMAX POLVO 17G', '1 SOBRE DE CONTUMAX POLVO 17G', 56.77, 18.92, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
