-- Seed inventory items for "Ingredientes de Cocina" (id=6) and "Alimentación" (id=7)
-- Generated sample data for hospital kitchen operations

-- Ingredientes de Cocina (raw kitchen ingredients)
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at) VALUES
-- Granos y cereales
(6, 'ARROZ BLANCO (LIBRA)', 'ARROZ BLANCO DE PRIMERA CALIDAD', 5.50, 3.50, 100, 25, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'FRIJOL NEGRO (LIBRA)', 'FRIJOL NEGRO SECO', 7.00, 4.50, 80, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PASTA ESPAGUETI (400G)', 'PASTA TIPO ESPAGUETI', 8.50, 5.00, 40, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PASTA CODITOS (400G)', 'PASTA TIPO CODITOS', 8.50, 5.00, 30, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'AVENA EN HOJUELAS (LIBRA)', 'AVENA EN HOJUELAS PARA COCINAR', 6.00, 3.80, 25, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'HARINA DE MAIZ (LIBRA)', 'HARINA DE MAIZ PARA TORTILLAS', 4.50, 2.80, 50, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PAN DE SANDWICH (BOLSA)', 'PAN BLANCO DE MOLDE PARA SANDWICH', 18.00, 12.00, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'TORTILLAS DE MAIZ (DOCENA)', 'TORTILLAS DE MAIZ FRESCAS', 8.00, 5.00, 20, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Proteinas
(6, 'POLLO ENTERO (LIBRA)', 'POLLO FRESCO ENTERO', 14.00, 9.00, 50, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PECHUGA DE POLLO (LIBRA)', 'PECHUGA DE POLLO SIN HUESO', 22.00, 15.00, 40, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'CARNE DE RES (LIBRA)', 'CARNE DE RES PARA GUISAR', 30.00, 20.00, 30, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'HUEVOS (CARTON 30 UNIDADES)', 'HUEVOS DE GALLINA FRESCOS', 45.00, 30.00, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'SALCHICHA (LIBRA)', 'SALCHICHA DE POLLO', 16.00, 10.00, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Lacteos
(6, 'LECHE ENTERA (LITRO)', 'LECHE PASTEURIZADA ENTERA', 12.00, 8.00, 30, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'QUESO FRESCO (LIBRA)', 'QUESO FRESCO DE VACA', 25.00, 16.00, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'CREMA (BOLSA 250ML)', 'CREMA FRESCA PARA COCINAR', 10.00, 6.50, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'MANTEQUILLA (BARRA 250G)', 'MANTEQUILLA SIN SAL', 18.00, 12.00, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Verduras y frutas
(6, 'TOMATE (LIBRA)', 'TOMATE FRESCO DE COCINA', 6.00, 3.50, 40, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'CEBOLLA (LIBRA)', 'CEBOLLA BLANCA', 5.00, 3.00, 35, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PAPA (LIBRA)', 'PAPA PARA COCINAR', 5.50, 3.50, 40, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'ZANAHORIA (LIBRA)', 'ZANAHORIA FRESCA', 4.00, 2.50, 25, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'GUISQUIL (LIBRA)', 'GUISQUIL FRESCO', 4.50, 2.80, 20, 10, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'LECHUGA (UNIDAD)', 'LECHUGA FRESCA PARA ENSALADA', 6.00, 3.50, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'PLATANO MADURO (UNIDAD)', 'PLATANO MADURO PARA COCINAR', 2.50, 1.50, 40, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'BANANO (UNIDAD)', 'BANANO FRESCO', 1.50, 0.80, 60, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'NARANJA (UNIDAD)', 'NARANJA PARA JUGO', 2.00, 1.00, 50, 20, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'LIMON (UNIDAD)', 'LIMON PERSA', 1.00, 0.50, 40, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Aceites, condimentos y basicos
(6, 'ACEITE VEGETAL (LITRO)', 'ACEITE VEGETAL PARA COCINAR', 22.00, 15.00, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'AZUCAR (LIBRA)', 'AZUCAR BLANCA REFINADA', 5.00, 3.00, 40, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'SAL (LIBRA)', 'SAL DE COCINA', 2.50, 1.50, 20, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'CONSOMME DE POLLO (SOBRE)', 'CONSOMME DE POLLO EN POLVO', 3.00, 1.80, 50, 15, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'SALSA DE TOMATE (BOTELLA 400ML)', 'SALSA DE TOMATE PARA COCINAR', 12.00, 7.50, 15, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'MAYONESA (FRASCO 400G)', 'MAYONESA PARA COCINAR', 20.00, 13.00, 8, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Bebidas
(6, 'CAFE MOLIDO (LIBRA)', 'CAFE MOLIDO TOSTADO', 30.00, 20.00, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'TE EN BOLSITAS (CAJA 25 UNIDADES)', 'TE DE MANZANILLA O HIERBAS', 15.00, 9.00, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'AGUA PURA (GARAFON 5 GALONES)', 'AGUA PURIFICADA PARA CONSUMO', 25.00, 15.00, 8, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'JUGO DE NARANJA (LITRO)', 'JUGO DE NARANJA NATURAL', 15.00, 9.00, 12, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'LECHE EN POLVO (BOLSA 400G)', 'LECHE EN POLVO INSTANTANEA', 28.00, 18.00, 10, 3, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Alimentación (prepared meals and diets served to patients)
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at) VALUES
-- Tiempos de comida regulares
(7, 'DESAYUNO REGULAR', 'DESAYUNO COMPLETO: HUEVOS, FRIJOLES, PLATANO, PAN, CAFE O JUGO', 65.00, 35.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'ALMUERZO REGULAR', 'ALMUERZO COMPLETO: SOPA, PLATO FUERTE CON PROTEINA, ARROZ, ENSALADA, REFRESCO', 85.00, 45.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'CENA REGULAR', 'CENA COMPLETA: PLATO FUERTE LIVIANO, ACOMPANAMIENTO, BEBIDA', 70.00, 38.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'MERIENDA', 'MERIENDA: FRUTA, GALLETAS O SANDWICH PEQUENO CON BEBIDA', 30.00, 15.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'REFACCION NOCTURNA', 'REFACCION NOCTURNA LIVIANA: CEREAL, FRUTA O PAN CON BEBIDA CALIENTE', 25.00, 12.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Dietas especiales
(7, 'DESAYUNO DIETA DIABETICA', 'DESAYUNO PARA PACIENTE DIABETICO: HUEVOS, FRIJOLES, PAN INTEGRAL, BEBIDA SIN AZUCAR', 75.00, 40.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'ALMUERZO DIETA DIABETICA', 'ALMUERZO PARA PACIENTE DIABETICO: PROTEINA, VEGETALES, PORCION CONTROLADA DE CARBOHIDRATOS', 95.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'CENA DIETA DIABETICA', 'CENA PARA PACIENTE DIABETICO: PLATO LIVIANO, VEGETALES, BEBIDA SIN AZUCAR', 80.00, 42.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'DIETA BLANDA (TIEMPO DE COMIDA)', 'COMIDA DE DIETA BLANDA: ALIMENTOS SUAVES, FACILES DE DIGERIR', 70.00, 38.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'DIETA LIQUIDA (TIEMPO DE COMIDA)', 'DIETA LIQUIDA: CALDOS, JUGOS, GELATINA, BEBIDAS NUTRITIVAS', 50.00, 25.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'DIETA HIPOSODICA (TIEMPO DE COMIDA)', 'COMIDA BAJA EN SODIO PARA PACIENTES CON HIPERTENSION', 80.00, 42.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Extras
(7, 'SUPLEMENTO NUTRICIONAL', 'BEBIDA DE SUPLEMENTO NUTRICIONAL TIPO ENSURE O SIMILAR', 45.00, 28.00, 20, 5, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'PORCION DE FRUTA EXTRA', 'PORCION ADICIONAL DE FRUTA FRESCA DE TEMPORADA', 15.00, 8.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'BEBIDA CALIENTE EXTRA', 'CAFE, TE O CHOCOLATE CALIENTE ADICIONAL', 10.00, 5.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'JUGO NATURAL EXTRA', 'VASO DE JUGO NATURAL DE NARANJA O FRUTA DE TEMPORADA', 15.00, 8.00, 0, 0, 'FLAT', NULL, NULL, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
