-- ============================================================================
-- SEED FILE 02: Triage Codes, Rooms, Inventory
-- ============================================================================

SET session_replication_role = replica;

-- ============================================================================
-- STEP 8: CREATE TRIAGE CODES
-- ============================================================================
-- Columns: code, color (#RRGGBB), description, display_order
INSERT INTO triage_codes (code, color, description, display_order, created_at, updated_at) VALUES
('A', '#FF0000', 'Critical - Immediate attention required', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B', '#FFA500', 'Urgent - Requires prompt attention', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C', '#FFFF00', 'Less Urgent - Can wait for care', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('D', '#00FF00', 'Non-Urgent - Minor issues', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('E', '#0000FF', 'Referral - Scheduled admission', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================================
-- STEP 9: CREATE ROOMS
-- ============================================================================
-- Room types: PRIVATE (1 bed), SHARED (multiple beds)
-- Room gender: MALE, FEMALE
INSERT INTO rooms (number, type, gender, capacity, price, created_at, updated_at) VALUES
-- First floor - Women's rooms
('101', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('102', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('103', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('104', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('105', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('106', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('107', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('108', 'SHARED', 'FEMALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('109', 'PRIVATE', 'FEMALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('110', 'PRIVATE', 'FEMALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Second floor - Men's rooms
('201', 'PRIVATE', 'MALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('202', 'PRIVATE', 'MALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('203', 'PRIVATE', 'MALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('204', 'PRIVATE', 'MALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Third floor - Men's rooms
('301', 'PRIVATE', 'MALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('302', 'PRIVATE', 'MALE', 1, 1100.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('303', 'SHARED', 'MALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('304', 'SHARED', 'MALE', 2, 950.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================================
-- STEP 10: RESEED INVENTORY CATEGORIES AND ITEMS
-- ============================================================================
-- Categories are wiped by TRUNCATE users CASCADE (via created_by/updated_by FKs)
-- so we must re-insert them along with all inventory items.

INSERT INTO inventory_categories (name, description, display_order, active, created_at, updated_at) VALUES
('Medicamentos', 'Medication and pharmaceutical supplies', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Material y Equipo', 'Materials and equipment', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Laboratorios', 'Laboratory services and supplies', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Servicios', 'Hospital services', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Personal Especial', 'Specialized personnel services', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ingredientes de Cocina', 'Kitchen ingredients', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Alimentación', 'Food served to patients', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Medicamentos (category: Medicamentos)
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
-- Antipsychotics
('TABLETA DE QUTIAPINA (QUETIOXAL 300 MG)', 'TABLETA DE QUETIOXAL 300 MG', 47.50, 15.83, 25, 10, 'FLAT', NULL::VARCHAR, NULL::INT, true),
('AMPOLLA DE OLANZAPINA (ZYPREXA IM 10 MG)', 'AMPOLLA DE OLANZAPINA (ZYPREXA IM 10 MG)', 525.00, 175.00, 12, 3, 'FLAT', NULL, NULL, true),
('CAJA DE OLANZAPINA (ZYPREXA 5 MG X 14 TABLETAS)', 'CAJA DE ZYPREXA 5 MG X 14 TABLETAS', 1907.80, 635.96, 3, 1, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL OLANZAPINA (ZYPREXA 5 MG)', 'TABLETA INDIVIDUAL OLANZAPINA (ZYPREXA 5 MG)', 136.27, 45.43, 9, 5, 'FLAT', NULL, NULL, true),
('TABLETA DE SEROQUEL (QUETIAPINA 100 MG)', 'TABLETA DE SEROQUEL (QUETIAPINA 100 MG)', 72.03, 24.01, 30, 10, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL ROYALINE 5 MG', 'TABLETA INDIVIDUAL ROYALINE TABLETAS 5 MG ROYALINE 5 MG', 7.56, 2.52, 16, 5, 'FLAT', NULL, NULL, true),
('CAJA DE ARIPIPRAZOL (PRI PAX 5 MG X 30 COMPRIMIDOS)', 'CAJA DE ARIPIPRAZOL (PRI PAX 5 MG X 30 COMPRIMIDOS)', 485.76, 161.92, 1, 1, 'FLAT', NULL, NULL, true),
('1 FRASCO DE ARIPIPRAZOL DE 150 ML', '1 FRASCO DE ARIPIPRAZOL DE 150 ML', 819.00, 273.00, 0, 1, 'FLAT', NULL, NULL, true),
-- Benzodiazepines and sedatives
('AMPOLLA MIDAZOLAM (DORMICUM 15MG/3ML)', 'AMPOLLA MIDAZOLAM (DORMICUM 15MG/3ML)', 196.47, 65.49, 14, 5, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL MIDAZOLAM DORMICUM 15 MG', 'TABLETA INDIVIDUAL MIDAZOLAM DORMICUM 15 MG', 22.29, 7.43, 30, 10, 'FLAT', NULL, NULL, true),
('CAJA MIDAZOLAM (DORMICUM 15 MG X 30 TABLETAS)', 'CAJA MIDAZOLAM (DORMICUM 15 MG X 30 TABLETAS)', 668.31, 222.77, 1, 1, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG)', 'TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG)', 17.32, 4.33, 28, 10, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG) II', 'TABLETA INDIVIDUAL CLONAZEPAM (RIVOTRIL 2 MG)', 12.99, 4.33, 27, 10, 'FLAT', NULL, NULL, true),
('AMPOLLA DE DIAZEPAM DORMICUM 10 MG', 'AMPOLLA DE DIAZEPAM DORMICUM 10 MG', 10.62, 3.54, 2, 2, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL BIPERIDENO HC (BIPARK 2 MG)', 'TABLETA INDIVIDUAL BIPERIDENO HC (BIPARK 2 MG)', 13.50, 4.50, 45, 10, 'FLAT', NULL, NULL, true),
-- Pregabalin
('TABLETA PREGABALINA (MARTESIA 75 MG)', 'TABLETA PREGABALINA (MARTESIA 75 MG)', 46.48, 11.62, 18, 5, 'FLAT', NULL, NULL, true),
('TABLETA PREGABALINA (ASTIK 75 MG)', 'TABLETA PREGABALINA (ASTIK 75 MG)', 29.49, 9.83, 4, 3, 'FLAT', NULL, NULL, true),
-- Antidepressants (SSRIs)
('TABLETA INDIVIDUAL DE SEROLUX (SERTRALINA 50 MG)', 'TABLETA INDIVIDUAL DE SEROLUX (SERTRALINA 50 MG)', 37.78, 12.59, 25, 10, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL ALTRULINE (SERTRALINA) 50 MG', 'TABLETA INDIVIDUAL ALTRULINE (SERTRALINA) 50 MG', 87.78, 29.26, 27, 10, 'FLAT', NULL, NULL, true),
-- IV solutions
('SOLUCIÓN SALINA DE 100 ML', 'SOLUCIÓN SALINA 100 ML', 30.00, 10.00, 18, 5, 'FLAT', NULL, NULL, true),
('SOLUCIÓN SALINA DE 250 ML', 'SOLUCIÓN SALINA DE 250 ML', 24.84, 8.28, 11, 5, 'FLAT', NULL, NULL, true),
('SOLUCIÓN SALINA DE 500 ML', 'SOLUCIÓN SALINA DE 500 ML', 28.98, 9.66, 0, 5, 'FLAT', NULL, NULL, true),
('SOLUCIÓN MIXTA DE 500 ML', 'SOLUCIÓN MIXTA DE 500 ML', 43.20, 14.40, 1, 2, 'FLAT', NULL, NULL, true),
('SOLUCIÓN HARTMAN 1000 ML', 'SOLUCIÓN HARTMAN 1000 ML', 48.00, 16.00, 4, 2, 'FLAT', NULL, NULL, true),
('SOLUCIÓN DEXTROSA AL 5% 500 ML', 'SOLUCIÓN DEXTROSA AL 5% 500 ML', 33.60, 11.20, 5, 2, 'FLAT', NULL, NULL, true),
('AGUA ESTÉRIL PARA INYECCIÓN 100 ML', 'AGUA ESTÉRIL PARA INYECCIÓN 100 ML', 33.60, 11.20, 2, 2, 'FLAT', NULL, NULL, true),
('AGUA ESTÉRIL INYECTABLE 500 ML', 'AGUA ESTÉRIL INYECTABLE 500 ML', 78.00, 26.00, 1, 2, 'FLAT', NULL, NULL, true),
-- Anesthetics
('LIDOCAINA CON EPINEFRINA 10 ML', 'LIDOCAINA CON EPINEFRINA 10 ML', 27.00, 9.00, 4, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA PROPOFOL-LIPURO 1%', 'AMPOLLA PROPOFOL-LIPURO 1%', 81.00, 27.00, 5, 2, 'FLAT', NULL, NULL, true),
-- Corticosteroids
('TABLETA INDIVIDUAL DEXAMETASONA 0.5 MG', 'DEXAMETASONA 0.5 MG', 5.44, 1.36, 36, 10, 'FLAT', NULL, NULL, true),
('DEXAMETASONA, AMPOLLA 8 MG/2 ML', 'DEXAMETASONA, AMPOLLA 8 MG/2 ML', 126.45, 42.15, 1, 2, 'FLAT', NULL, NULL, true),
('DEXAMETASONA AMPOLLA 4MG', 'DEXAMETASONA AMPOLLA 4MG', 75.81, 25.27, 5, 2, 'FLAT', NULL, NULL, true),
-- Antihistamines and tópicals
('CALADRYL CLEAR LOCIÓN 100 ML', 'CALADRYL CLEAR LOCIÓN 100 ML', 246.21, 82.07, 0, 1, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL DE CLORHIDRATO DE DIFENHIDRAMINA 25 MG', 'TABLETA INDIVIDUAL DE CLORHIDRATO DE DIFENHIDRAMINA 25 MG', 8.31, 2.77, 5, 3, 'FLAT', NULL, NULL, true),
('HISTAPRIN AMPOLLA 10 MG', 'HISTAPRIN AMPOLLA 10 MG', 130.53, 43.51, 1, 1, 'FLAT', NULL, NULL, true),
-- Analgesics and anti-inflammatories
('TABLETA INDIVIDUAL DE DICLOFENACO 50 MG', 'TABLETA INDIVIDUAL DE DICLOFENACO 50 MG', 3.60, 1.20, 7, 5, 'FLAT', NULL, NULL, true),
('TABLETA INDIVIDUAL DE ACETAMINOFÉN 50 MG', 'TABLETA INDIVIDUAL DE ACETAMINOFÉN 50 MG', 2.10, 0.70, 8, 5, 'FLAT', NULL, NULL, true),
-- Electrolytes and emergency medications
('AMPOLLA CLORURO DE POTASIO 5 ML (200 MG/ML)', 'AMPOLLA DE CLORURO DE POTASIO 5 ML (200 MG/ML)', 11.40, 3.80, 1, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE CLORURO DE POTASIO 20MEQ/10 ML', 'AMPOLLA DE CLORURO DE POTASIO 20 MEQ/10 ML', 10.50, 3.50, 25, 5, 'FLAT', NULL, NULL, true),
('AMPOLLA DE CLORURO DE SODIO 20% (200MG/10ML)', 'AMPOLLA DE CLORURO DE SODIO 20% (200MG/10ML)', 12.00, 4.00, 14, 5, 'FLAT', NULL, NULL, true),
('AMPOLLA DE BICARBONATO DE SODIO 7%', 'AMPOLLA DE BICARBONATO DE SODIO 7%', 76.50, 25.50, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE SULFATO DE MAGNESIO 50%', 'AMPOLLA DE SULFATO DE MAGNESIO 50%', 14.40, 4.80, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE AMINOFILINA 250MG/5ML', 'AMPOLLA DE AMINOFILINA 250MG/5ML', 15.60, 5.20, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE SULFATO DE ATROPINA 0.5MG/1ML', 'AMPOLLA DE SULFATO DE ATROPINA 0.5MG/1ML', 11.40, 3.80, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE EPINEFRINA 1 MG/1 ML (ADRENALINA)', 'AMPOLLA DE EPINEFRINA 1 MG/1 ML (ADRENALINA)', 11.70, 3.90, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE NALOXONA 0.4MG/1ML', 'AMPOLLA DE NALOXONA 0.4MG/1ML', 35.25, 11.75, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE FUROSEMIDA 20MG/2ML', 'AMPOLLA DE FUROSEMIDA 20MG/2ML', 7.50, 2.50, 5, 2, 'FLAT', NULL, NULL, true),
('AMPOLLA DE FLUMAZENIL 0.1MG/ML', 'AMPOLLA DE FLUMAZENIL 0.1MG/ML', 390.00, 130.00, 2, 1, 'FLAT', NULL, NULL, true),
('AMPOLLA DE INOTROPISA 5 ML (DOPAMINA)', 'AMPOLLA DE INOTROPISA 5 ML (DOPAMINA)', 255.00, 85.00, 5, 2, 'FLAT', NULL, NULL, true),
-- GI
('1 SOBRE DE CONTUMAX POLVO 17G', '1 SOBRE DE CONTUMAX POLVO 17G', 56.77, 18.92, 15, 5, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Medicamentos';

-- Material y Equipo
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
-- Time-based equipment usage
('MONITOR CARDIACO', 'USO MONITOR CARDIACO (1 HORA)', 250.00, 250.00, 0, 0, 'TIME_BASED', 'HOURS'::VARCHAR, 1::INT, true),
('BOMBA DE INFUSIÓN', 'USO DE BOMBA DE INFUSIÓN (1 HORA)', 250.00, 250.00, 0, 0, 'TIME_BASED', 'HOURS', 1, true),
('OXÍGENO', 'USO OXÍGENO (10 MINUTOS)', 117.00, 16.20, 0, 0, 'TIME_BASED', 'MINUTES', 10, true),
-- Flat-priced equipment and services
('EKG', 'EKG', 265.00, 265.00, 0, 0, 'FLAT', NULL, NULL, true),
('USO DE DESFIBRILADOR', 'USO DE DESFIBRILADOR', 3000.00, 0.00, 0, 0, 'FLAT', NULL, NULL, true),
('USO DE GLUCÓMETRO', 'USO DE GLUCÓMETRO', 49.98, 12.09, 50, 5, 'FLAT', NULL, NULL, true),
-- Syringes
('JERINGAS DESCARTABLES 3 CC', 'JERINGAS DESCARTABLES 3 CC 21 G', 2.25, 0.56, 83, 10, 'FLAT', NULL, NULL, true),
('JERINGAS DESCARTABLES DE 5 CC', 'JERINGAS DESCARTABLES DE 5 CC 21 G', 2.35, 0.58, 62, 10, 'FLAT', NULL, NULL, true),
('JERINGAS DESCARTABLES 10 CC', 'JERINGAS DESCARTABLES 10 CC 21 G', 3.60, 0.90, 72, 10, 'FLAT', NULL, NULL, true),
('JERINGA DE INSULINA DE 1 CC', 'JERINGA DE INSULINA DE 1 CC', 3.40, 0.85, 97, 10, 'FLAT', NULL, NULL, true),
-- Aspiration probes
('SONDA DE ASPIRACIÓN NO. 12', 'SONDA DE ASPIRACIÓN NO. 12 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true),
('SONDA DE ASPIRACIÓN NO. 14', 'SONDA DE ASPIRACIÓN NO. 14 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true),
('SONDA DE ASPIRACIÓN NO. 16', 'SONDA DE ASPIRACIÓN NO. 16 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true),
('SONDA DE ASPIRACIÓN NO. 18', 'SONDA DE ASPIRACIÓN NO. 18 OPERSON', 9.00, 2.25, 3, 2, 'FLAT', NULL, NULL, true),
-- IV catheters
('CATÉTER INTRAVENOSO NO. 18', 'CATÉTER INTRAVENOSO NO. 18 (ANGIOCATH) NIPRO', 17.00, 4.25, 29, 5, 'FLAT', NULL, NULL, true),
('CATÉTER INTRAVENOSO NO. 20', 'CATÉTER INTRAVENOSO NO. 20 (ANGIOCATH) NIPRO', 17.00, 4.25, 18, 5, 'FLAT', NULL, NULL, true),
('CATÉTER INTRAVENOSO NO. 22', 'CATÉTER INTRAVENOSO NO. 22 (ANGIOCATH) NIPRO', 17.00, 4.50, 25, 5, 'FLAT', NULL, NULL, true),
('CATÉTER INTRAVENOSO NO. 24', 'CATÉTER INTRAVENOSO NO. 24 (ANGIOCATH) NIPRO', 17.00, 4.50, 22, 5, 'FLAT', NULL, NULL, true),
-- IV supplies
('SELLOS DE HEPARINA', 'SELLOS DE HEPARINA - TAPON IN LUER-LOK BARAUN', 7.20, 1.80, 17, 5, 'FLAT', NULL, NULL, true),
('VENOSETH', 'VENOSETH (EQUIPO DE SUERO) PARKINGTON', 10.40, 2.60, 4, 2, 'FLAT', NULL, NULL, true),
-- Endotracheal tubes
('TUBOS ENDOTRAQUEALES #7', 'TUBOS ENDOTRAQUEALES #7, OPERSON', 45.00, 11.25, 3, 2, 'FLAT', NULL, NULL, true),
('TUBOS ENDOTRAQUEALES #7.5', 'TUBOS ENDOTRAQUEALES #7.5, OPERSON', 45.00, 11.25, 3, 2, 'FLAT', NULL, NULL, true),
('TUBOS ENDOTRAQUEALES NO. 8', 'TUBOS ENDOTRAQUEALES NO. 8', 88.00, 22.00, 5, 2, 'FLAT', NULL, NULL, true),
-- Sutures
('SUTURAS NYLON # 2-0, 75 CM', 'SUTURAS NYLON # 2-0, 75 CM, ATRAMAT', 39.60, 9.99, 12, 5, 'FLAT', NULL, NULL, true),
('SUTURAS NYLON # 3-0, 75 CM', 'SUTURAS NYLON # 3-0, 75 CM, CE-24 ATRAMAT', 39.60, 9.90, 12, 5, 'FLAT', NULL, NULL, true),
('SUTURAS PGA # 2-0, 75 CM', 'SUTURAS # 3-0, 75 CM, G-37 AHUSADA, ATRAMAT', 63.12, 15.78, 12, 5, 'FLAT', NULL, NULL, true),
('SUTURAS CATGUT SIMPLE # 2-0, 75 CM', 'SUTURAS CATGUT SIMPLE # 2-0, 75 CM, G-37 GRUESA ATRAMAT', 59.00, 14.75, 12, 5, 'FLAT', NULL, NULL, true),
('SUTURAS SEDA # 2-0, 75 CM', 'SUTURAS SEDA # 2-0, 75 CM, SR-26, ATRAMAT', 39.00, 9.75, 12, 5, 'FLAT', NULL, NULL, true),
-- Respiratory supplies
('CANULAS DE OXÍGENO BINASAL GRANDE', 'CANULAS DE OXÍGENO BINASAL GRANDE, OPERSON', 19.60, 4.90, 10, 3, 'FLAT', NULL, NULL, true),
('MASCARILLA P/NEBULIZAR ADULTO L', 'MASCARILLA P/NEBULIZAR ADULTO L, OPERSON', 54.00, 13.50, 11, 3, 'FLAT', NULL, NULL, true),
('MASCARILLA CON RESERVORIO', 'MASCARILLA CON RESERVORIO', 280.00, 70.00, 5, 2, 'FLAT', NULL, NULL, true),
-- PPE and masks
('MASCARILLAS 3 PLIEGOS', 'MASCARILLAS 3 PLIEGOS ELASTICAS AMBIDEM', 1.46, 0.36, 50, 20, 'FLAT', NULL, NULL, true),
-- Gloves
('GUANTES QUIRÚRGICOS NO. 6', 'GUANTES QUIRÚRGICOS NO. 6, AMBIDERM', 11.40, 2.85, 50, 10, 'FLAT', NULL, NULL, true),
('GUANTES QUIRÚRGICOS NO. 7', 'GUANTES QUIRÚRGICOS NO. 7, AMBIDERM', 11.40, 2.85, 49, 10, 'FLAT', NULL, NULL, true),
('GUANTES DESCARTABLES TALLA S', 'GUANTES DESCARTABLES TALLA S, PROTECT', 3.40, 0.85, 64, 10, 'FLAT', NULL, NULL, true),
('GUANTES DESCARTABLES TALLA L', 'GUANTES DESCARTABLES TALLA L, PROTECT', 3.40, 0.85, 47, 10, 'FLAT', NULL, NULL, true),
-- Foley catheters
('SONDA FOLEY NO. 14', 'SONDA FOLEY NO. 14, BALON 5-15 ML 2 VIAS, OPERSON', 30.00, 7.50, 10, 3, 'FLAT', NULL, NULL, true),
('SONDA FOLEY NO. 16', 'SONDA FOLEY NO. 16, BALON 5-15 ML 2 VIAS, OPERSON', 30.00, 7.50, 10, 3, 'FLAT', NULL, NULL, true),
-- Nasogastric probe
('SONDA NASOGÁSTRICA NO. 5', 'SONDA NASOGÁSTRICA NO. 5', 7.05, 2.35, 5, 2, 'FLAT', NULL, NULL, true),
-- Urine collection bags
('BOLSA RECOLECTORA DE ORINA PIERNA', 'BOLSA RECOLECTORA DE ORINA PIERNA 750 ML, OPERSON', 22.20, 5.55, 3, 2, 'FLAT', NULL, NULL, true),
('BOLSA RECOLECTORA DE ORINA CAMA', 'BOLSA RECOLECTORA DE ORINA CAMA 2000ML, PARKINGTON', 20.00, 5.00, 3, 2, 'FLAT', NULL, NULL, true),
-- General supplies
('BAJALENGUAS DE MADERA', 'BAJALENGUAS DE MADERA', 0.54, 0.13, 196, 20, 'FLAT', NULL, NULL, true),
('SONIGEL TUBO 125 GRAMOS', 'SONIGEL TUBO 125 GRAMOS DIQUIVA', 47.00, 11.75, 3, 2, 'FLAT', NULL, NULL, true),
-- Needles
('AGUJA HIPODÉRMICA NO. 23 G', 'AGUJA HIPODÉRMICA NO. 23 G', 4.00, 1.00, 196, 20, 'FLAT', NULL, NULL, true),
('AGUJA 18X1', 'AGUJA 18X1', 1.40, 0.35, 100, 20, 'FLAT', NULL, NULL, true),
-- Wound care and dressings
('GASAS ESTÉRILES', 'GASAS ESTÉRILES (UNIDAD)', 3.68, 0.92, 42, 20, 'FLAT', NULL, NULL, true),
('CURITAS CIRCULARES', 'CURITAS CIRCULARES', 0.56, 0.14, 127, 20, 'FLAT', NULL, NULL, true),
('VENDA GASA 3X10 Y', 'ROLLO DE VENDA GASA 3 X 10 Y.', 23.28, 5.82, 3, 2, 'FLAT', NULL, NULL, true),
('TEGADERM 3M', 'TEGADERM 3M, NEXCARE', 91.00, 22.75, 5, 2, 'FLAT', NULL, NULL, true),
('CAMPO ESTÉRIL', 'CAMPO ESTÉRIL', 64.00, 16.00, 12, 5, 'FLAT', NULL, NULL, true),
-- Electrodes and tapes
('ELECTRODOS', 'ELECTRODOS EKG', 4.74, 1.58, 37, 10, 'FLAT', NULL, NULL, true),
('MICROPORE', 'MICROPORE', 15.50, 15.50, 2, 2, 'FLAT', NULL, NULL, true),
('MICROPORE DE 1 PULGADA', 'MICROPORE DE 1 PULGADA', 34.00, 8.50, 5, 2, 'FLAT', NULL, NULL, true),
('ESPARADRAPO', 'ESPARADRAPO', 19.60, 4.90, 0, 2, 'FLAT', NULL, NULL, true),
-- Cleaning and hygiene
('ALCOHOL EN GEL 60 G', 'ALCOHOL EN GEL 60 G', 12.65, 12.65, 1, 2, 'FLAT', NULL, NULL, true),
('SOLUCIÓN DE CLORHEXIDINA 5%', 'GALON SOLUCIÓN DE CLORHEXIDINA 5%', 300.00, 300.00, 1, 1, 'FLAT', NULL, NULL, true),
('KIT DE HIGIENE', 'KIT DE HIGIENE', 125.00, 56.00, 4, 2, 'FLAT', NULL, NULL, true),
('1 TORUNDA DE ALGODON', '1 TORUNDA DE ALGODON', 2.00, 0.20, 60, 20, 'FLAT', NULL, NULL, true),
('10 CC ALCOHOL', 'ALCOHOL', 1.00, 0.20, 198, 20, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Material y Equipo';

-- Laboratorios
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
-- Chemistry panel
('ÁCIDO ÚRICO', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL::VARCHAR, NULL::INT, true),
('ALBUMINA', 'SUERO', 120.00, 40.00, 0, 0, 'FLAT', NULL, NULL, true),
('AMILASA', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
('BICARBONATO', 'SUERO', 900.00, 300.00, 0, 0, 'FLAT', NULL, NULL, true),
('BILIRUBINAS (TOTAL, DIRECTA E INDIRECTA)', 'SUERO', 240.00, 80.00, 0, 0, 'FLAT', NULL, NULL, true),
('CALCIO', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
('CLORUROS', 'SUERO', 240.00, 80.00, 0, 0, 'FLAT', NULL, NULL, true),
('CREATININA', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('FOSFATASA ACIDA PROSTATICA', 'SUERO', 375.00, 125.00, 0, 0, 'FLAT', NULL, NULL, true),
('FOSFATASA ACIDA TOTAL', 'SUERO', 500.00, 125.00, 0, 0, 'FLAT', NULL, NULL, true),
('FOSFATASA ALCALINA', 'SUERO', 180.00, 60.00, 0, 0, 'FLAT', NULL, NULL, true),
('GAMA GLUTAMIL TRANSFERASA (GGT)', 'SUERO', 240.00, 80.00, 0, 0, 'FLAT', NULL, NULL, true),
('GLUCOSA', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('MAGNESIO', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
('NITRÓGENO DE UREA', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('POTASIO', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
('PROTEÍNAS TOTALES', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('SODIO', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Lipid panel
('COLESTEROL HDL', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('COLESTEROL LDL', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('COLESTEROL TOTAL', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('COLESTEROL VLDL', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('TRIGLICÉRIDOS', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('PERFIL DE LÍPIDOS', 'SUERO', 600.00, 200.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Liver panel
('TGO', 'SUERO', 180.00, 60.00, 0, 0, 'FLAT', NULL, NULL, true),
('TGP', 'SUERO', 180.00, 60.00, 0, 0, 'FLAT', NULL, NULL, true),
('PRUEBAS HEPÁTICAS TGO-TGP-GGT', 'SUERO', 600.00, 200.00, 0, 0, 'FLAT', NULL, NULL, true),
('LIPASA', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
('LIPASA TOTALES', 'SUERO', 180.00, 60.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Cardiac markers
('CK-MB', 'SUERO', 300.00, 100.00, 0, 0, 'FLAT', NULL, NULL, true),
('CK-TOTAL', 'SUERO', 300.00, 100.00, 0, 0, 'FLAT', NULL, NULL, true),
('CK-MM', 'SUERO', 750.00, 250.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Coagulation
('DÍMERO D', 'PLASMA CITRATADO', 1500.00, 500.00, 0, 0, 'FLAT', NULL, NULL, true),
('PROTEÍNA C', 'PLASMA CITRATADO', 1050.00, 350.00, 0, 0, 'FLAT', NULL, NULL, true),
('TIEMPO DE PROTROMBINA TP', 'PLASMA CITRATADO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('TIEMPO PARCIAL DE TROMBOPLASTINA TPT', 'PLASMA CITRATADO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Hormones - Thyroid
('T3 LIBRE', 'SUERO', 390.00, 130.00, 0, 0, 'FLAT', NULL, NULL, true),
('T3 TRIYODOTIRONINA', 'SUERO', 240.00, 80.00, 0, 0, 'FLAT', NULL, NULL, true),
('T3-T4, TSH', 'SUERO', 675.00, 225.00, 0, 0, 'FLAT', NULL, NULL, true),
('T4 LIBRE', 'SUERO', 390.00, 130.00, 0, 0, 'FLAT', NULL, NULL, true),
('HORMONA ESTIMULANTE DE TIROIDES (TSH)', 'SUERO', 375.00, 125.00, 0, 0, 'FLAT', NULL, NULL, true),
('HORMONA T3-T4-TSH', 'SUERO', 675.00, 125.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Hormones - Other
('CORTISOL AM', 'SUERO', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('CORTISOL PM', 'SUERO', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('HORMONA DEL CRECIMIENTO', 'SUERO', 675.00, 225.00, 0, 0, 'FLAT', NULL, NULL, true),
('HORMONA PROGESTERONA (P4)', 'SUERO', 375.00, 125.00, 0, 0, 'FLAT', NULL, NULL, true),
('INSULINA', 'SUERO', 675.00, 225.00, 0, 0, 'FLAT', NULL, NULL, true),
('CURVA DE GLUCOSA 3 HRS', 'SUERO', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('CURVA DE INSULINA 3 HRS', 'SUERO', 1200.00, 400.00, 0, 0, 'FLAT', NULL, NULL, true),
('TESTOSTERONA (TE)', 'SUERO', 540.00, 180.00, 0, 0, 'FLAT', NULL, NULL, true),
('TESTOSTERONA LIBRE', 'SUERO', 540.00, 180.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Tumor markers
('CA-125', 'SUERO', 675.00, 225.00, 0, 0, 'FLAT', NULL, NULL, true),
('CA-15-3', 'SUERO', 675.00, 225.00, 0, 0, 'FLAT', NULL, NULL, true),
('CA-19-9', 'SUERO', 675.00, 225.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Infectious disease
('HEPATITIS A IgG', 'SUERO', 525.00, 175.00, 0, 0, 'FLAT', NULL, NULL, true),
('HEPATITIS B', 'SUERO', 525.00, 175.00, 0, 0, 'FLAT', NULL, NULL, true),
('HEPATITIS C', 'SUERO', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('CARGA VIRAL DE HCV', 'TUBO CON EDTA', 6000.00, 2000.00, 0, 0, 'FLAT', NULL, NULL, true),
('CARGA VIRAL DE HIV', 'TUBO CON EDTA', 4500.00, 1500.00, 0, 0, 'FLAT', NULL, NULL, true),
('CARGA VIRAL DE HBsAg', 'TUBO CON EDTA', 6000.00, 2000.00, 0, 0, 'FLAT', NULL, NULL, true),
('HIV 1 Y 2', 'SUERO', 375.00, 125.00, 0, 0, 'FLAT', NULL, NULL, true),
('TB COMPLEX', 'SUERO', 600.00, 200.00, 0, 0, 'FLAT', NULL, NULL, true),
('VDRL-RPR', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Hematology
('HEMATOLOGÍA COMPLETA', 'TUBO CON EDTA', 180.00, 60.00, 0, 0, 'FLAT', NULL, NULL, true),
('HEMOGLOBINA-HEMATOCRITO', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('HEMOGLOBINA GLICOSILADA', 'TUBO CON EDTA', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('GRUPO SANGUÍNEO Y FACTOR RH', 'TUBO CON EDTA', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('HIERRO CAPACIDAD DE FIJACION', 'SUERO', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('HIERRO SÉRICO', 'SUERO', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Iron and vitamins
('VITAMINA B-12', 'SUERO', 750.00, 250.00, 0, 0, 'FLAT', NULL, NULL, true),
('VITAMINA D', 'SUERO', 1050.00, 350.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Inflammatory markers
('PROTEÍNA C REACTIVA', 'SUERO', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('AMONIO', 'TUBO DE HEMATOLOGIA', 600.00, 200.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Drug levels and toxicology
('CARBAMAZEPINA (TEGRETOL)', 'SUERO', 540.00, 180.00, 0, 0, 'FLAT', NULL, NULL, true),
('ALCOHOLEMIA', 'TUBO CON EDTA', 1050.00, 350.00, 0, 0, 'FLAT', NULL, NULL, true),
('BENZODIAZEPINAS', 'ORINA', 600.00, 200.00, 0, 0, 'FLAT', NULL, NULL, true),
('COCAINA', 'ORINA FRESCA', 600.00, 200.00, 0, 0, 'FLAT', NULL, NULL, true),
('MARIGUANA', 'SUERO', 525.00, 175.00, 0, 0, 'FLAT', NULL, NULL, true),
('PANEL DE DROGAS', 'ORINA FRESCA', 1650.00, 550.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Cultures and urine/stool
('HEMOCULTIVO (CULTIVO EN SANGRE)', 'CALDO BHI', 450.00, 150.00, 0, 0, 'FLAT', NULL, NULL, true),
('ORINA COMPLETO', 'ORINA FRESCA', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('OROCULTIVO', 'ISOPADO', 300.00, 100.00, 0, 0, 'FLAT', NULL, NULL, true),
('UROCULTIVO', 'ORINA FRESCA', 300.00, 100.00, 0, 0, 'FLAT', NULL, NULL, true),
('HECES COMPLETO', 'HECES FRESCAS', 150.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Pregnancy and special
('PRUEBA DE EMBARAZO', 'SUERO', 225.00, 75.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Admission kit
('KIT DE INGRESO', 'KIT DE INGRESO (HEMATOLOGIA, GLUCOSA, CREATININA, NITRÓGENO DE UREA, PERFIL DE LÍPIDOS, TGO-TGP, SODIO, POTASIO, HORMONAS FT3, FT4 Y TSH, PANEL DE DROGAS EN ORINA, VITAMINA D)', 4950.00, 1650.00, 97, 10, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Laboratorios';

-- Servicios
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
('ATENCIÓN EMERGENCIA', 'ATENCIÓN EMERGENCIA', 900.00, 0.00, 0, 0, 'FLAT', NULL::VARCHAR, NULL::INT, true),
('KETAMINA AMBULATORIA', 'PROCEDIMIENTO DE KETAMINA', 1500.00, 0.00, 0, 0, 'FLAT', NULL, NULL, true),
('KETAMINA INTERNA', 'PROCEDIMIENTO DE KETAMINA INTERNA', 1100.00, 0.00, 0, 0, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Servicios';

-- Personal Especial
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
('ENFERMERA SOMBRA HOSPITAL', 'ENFERMERA SOMBRA HOSPITAL', 500.00, 300.00, 0, 0, 'FLAT', NULL::VARCHAR, NULL::INT, true),
('ENFERMERA SOMBRA DOMICILIO', 'ENFERMERA SOMBRA DOMICILIO', 650.00, 350.00, 0, 0, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Personal Especial';

-- Ingredientes de Cocina
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
-- Granos y cereales
('ARROZ BLANCO (LIBRA)', 'ARROZ BLANCO DE PRIMERA CALIDAD', 5.50, 3.50, 100, 25, 'FLAT', NULL::VARCHAR, NULL::INT, true),
('FRIJOL NEGRO (LIBRA)', 'FRIJOL NEGRO SECO', 7.00, 4.50, 80, 20, 'FLAT', NULL, NULL, true),
('PASTA ESPAGUETI (400G)', 'PASTA TIPO ESPAGUETI', 8.50, 5.00, 40, 10, 'FLAT', NULL, NULL, true),
('PASTA CODITOS (400G)', 'PASTA TIPO CODITOS', 8.50, 5.00, 30, 10, 'FLAT', NULL, NULL, true),
('AVENA EN HOJUELAS (LIBRA)', 'AVENA EN HOJUELAS PARA COCINAR', 6.00, 3.80, 25, 10, 'FLAT', NULL, NULL, true),
('HARINA DE MAÍZ (LIBRA)', 'HARINA DE MAÍZ PARA TORTILLAS', 4.50, 2.80, 50, 15, 'FLAT', NULL, NULL, true),
('PAN DE SANDWICH (BOLSA)', 'PAN BLANCO DE MOLDE PARA SANDWICH', 18.00, 12.00, 15, 5, 'FLAT', NULL, NULL, true),
('TORTILLAS DE MAÍZ (DOCENA)', 'TORTILLAS DE MAÍZ FRESCAS', 8.00, 5.00, 20, 10, 'FLAT', NULL, NULL, true),
-- Proteínas
('POLLO ENTERO (LIBRA)', 'POLLO FRESCO ENTERO', 14.00, 9.00, 50, 15, 'FLAT', NULL, NULL, true),
('PECHUGA DE POLLO (LIBRA)', 'PECHUGA DE POLLO SIN HUESO', 22.00, 15.00, 40, 10, 'FLAT', NULL, NULL, true),
('CARNE DE RES (LIBRA)', 'CARNE DE RES PARA GUISAR', 30.00, 20.00, 30, 10, 'FLAT', NULL, NULL, true),
('HUEVOS (CARTON 30 UNIDADES)', 'HUEVOS DE GALLINA FRESCOS', 45.00, 30.00, 10, 3, 'FLAT', NULL, NULL, true),
('SALCHICHA (LIBRA)', 'SALCHICHA DE POLLO', 16.00, 10.00, 15, 5, 'FLAT', NULL, NULL, true),
-- Lácteos
('LECHE ENTERA (LITRO)', 'LECHE PASTEURIZADA ENTERA', 12.00, 8.00, 30, 10, 'FLAT', NULL, NULL, true),
('QUESO FRESCO (LIBRA)', 'QUESO FRESCO DE VACA', 25.00, 16.00, 10, 3, 'FLAT', NULL, NULL, true),
('CREMA (BOLSA 250ML)', 'CREMA FRESCA PARA COCINAR', 10.00, 6.50, 15, 5, 'FLAT', NULL, NULL, true),
('MANTEQUILLA (BARRA 250G)', 'MANTEQUILLA SIN SAL', 18.00, 12.00, 10, 3, 'FLAT', NULL, NULL, true),
-- Verduras y frutas
('TOMATE (LIBRA)', 'TOMATE FRESCO DE COCINA', 6.00, 3.50, 40, 15, 'FLAT', NULL, NULL, true),
('CEBOLLA (LIBRA)', 'CEBOLLA BLANCA', 5.00, 3.00, 35, 10, 'FLAT', NULL, NULL, true),
('PAPA (LIBRA)', 'PAPA PARA COCINAR', 5.50, 3.50, 40, 10, 'FLAT', NULL, NULL, true),
('ZANAHORIA (LIBRA)', 'ZANAHORIA FRESCA', 4.00, 2.50, 25, 10, 'FLAT', NULL, NULL, true),
('GUISQUIL (LIBRA)', 'GUISQUIL FRESCO', 4.50, 2.80, 20, 10, 'FLAT', NULL, NULL, true),
('LECHUGA (UNIDAD)', 'LECHUGA FRESCA PARA ENSALADA', 6.00, 3.50, 15, 5, 'FLAT', NULL, NULL, true),
('PLÁTANO MADURO (UNIDAD)', 'PLÁTANO MADURO PARA COCINAR', 2.50, 1.50, 40, 15, 'FLAT', NULL, NULL, true),
('BANANO (UNIDAD)', 'BANANO FRESCO', 1.50, 0.80, 60, 20, 'FLAT', NULL, NULL, true),
('NARANJA (UNIDAD)', 'NARANJA PARA JUGO', 2.00, 1.00, 50, 20, 'FLAT', NULL, NULL, true),
('LIMÓN (UNIDAD)', 'LIMÓN PERSA', 1.00, 0.50, 40, 15, 'FLAT', NULL, NULL, true),
-- Aceites, condimentos y básicos
('ACEITE VEGETAL (LITRO)', 'ACEITE VEGETAL PARA COCINAR', 22.00, 15.00, 15, 5, 'FLAT', NULL, NULL, true),
('AZÚCAR (LIBRA)', 'AZÚCAR BLANCA REFINADA', 5.00, 3.00, 40, 15, 'FLAT', NULL, NULL, true),
('SAL (LIBRA)', 'SAL DE COCINA', 2.50, 1.50, 20, 5, 'FLAT', NULL, NULL, true),
('CONSOMÉ DE POLLO (SOBRE)', 'CONSOMÉ DE POLLO EN POLVO', 3.00, 1.80, 50, 15, 'FLAT', NULL, NULL, true),
('SALSA DE TOMATE (BOTELLA 400ML)', 'SALSA DE TOMATE PARA COCINAR', 12.00, 7.50, 15, 5, 'FLAT', NULL, NULL, true),
('MAYONESA (FRASCO 400G)', 'MAYONESA PARA COCINAR', 20.00, 13.00, 8, 3, 'FLAT', NULL, NULL, true),
-- Bebidas
('CAFÉ MOLIDO (LIBRA)', 'CAFÉ MOLIDO TOSTADO', 30.00, 20.00, 10, 3, 'FLAT', NULL, NULL, true),
('TÉ EN BOLSITAS (CAJA 25 UNIDADES)', 'TÉ DE MANZANILLA O HIERBAS', 15.00, 9.00, 10, 3, 'FLAT', NULL, NULL, true),
('AGUA PURA (GARRAFÓN 5 GALONES)', 'AGUA PURIFICADA PARA CONSUMO', 25.00, 15.00, 8, 3, 'FLAT', NULL, NULL, true),
('JUGO DE NARANJA (LITRO)', 'JUGO DE NARANJA NATURAL', 15.00, 9.00, 12, 5, 'FLAT', NULL, NULL, true),
('LECHE EN POLVO (BOLSA 400G)', 'LECHE EN POLVO INSTANTÁNEA', 28.00, 18.00, 10, 3, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Ingredientes de Cocina';

-- Alimentación
INSERT INTO inventory_items (category_id, name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active, created_at, updated_at)
SELECT c.id, v.name, v.description, v.price, v.cost, v.quantity, v.restock_level, v.pricing_type, v.time_unit, v.time_interval, v.active, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM inventory_categories c,
(VALUES
-- Tiempos de comida regulares
('DESAYUNO REGULAR', 'DESAYUNO COMPLETO: HUEVOS, FRIJOLES, PLÁTANO, PAN, CAFÉ O JUGO', 65.00, 35.00, 0, 0, 'FLAT', NULL::VARCHAR, NULL::INT, true),
('ALMUERZO REGULAR', 'ALMUERZO COMPLETO: SOPA, PLATO FUERTE CON PROTEINA, ARROZ, ENSALADA, REFRESCO', 85.00, 45.00, 0, 0, 'FLAT', NULL, NULL, true),
('CENA REGULAR', 'CENA COMPLETA: PLATO FUERTE LIVIANO, ACOMPAÑAMIENTO, BEBIDA', 70.00, 38.00, 0, 0, 'FLAT', NULL, NULL, true),
('MERIENDA', 'MERIENDA: FRUTA, GALLETAS O SANDWICH PEQUEÑO CON BEBIDA', 30.00, 15.00, 0, 0, 'FLAT', NULL, NULL, true),
('REFACCIÓN NOCTURNA', 'REFACCIÓN NOCTURNA LIVIANA: CEREAL, FRUTA O PAN CON BEBIDA CALIENTE', 25.00, 12.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Dietas especiales
('DESAYUNO DIETA DIABÉTICA', 'DESAYUNO PARA PACIENTE DIABÉTICO: HUEVOS, FRIJOLES, PAN INTEGRAL, BEBIDA SIN AZÚCAR', 75.00, 40.00, 0, 0, 'FLAT', NULL, NULL, true),
('ALMUERZO DIETA DIABÉTICA', 'ALMUERZO PARA PACIENTE DIABÉTICO: PROTEINA, VEGETALES, PORCIÓN CONTROLADA DE CARBOHIDRATOS', 95.00, 50.00, 0, 0, 'FLAT', NULL, NULL, true),
('CENA DIETA DIABÉTICA', 'CENA PARA PACIENTE DIABÉTICO: PLATO LIVIANO, VEGETALES, BEBIDA SIN AZÚCAR', 80.00, 42.00, 0, 0, 'FLAT', NULL, NULL, true),
('DIETA BLANDA (TIEMPO DE COMIDA)', 'COMIDA DE DIETA BLANDA: ALIMENTOS SUAVES, FÁCILES DE DIGERIR', 70.00, 38.00, 0, 0, 'FLAT', NULL, NULL, true),
('DIETA LÍQUIDA (TIEMPO DE COMIDA)', 'DIETA LÍQUIDA: CALDOS, JUGOS, GELATINA, BEBIDAS NUTRITIVAS', 50.00, 25.00, 0, 0, 'FLAT', NULL, NULL, true),
('DIETA HIPOSÓDICA (TIEMPO DE COMIDA)', 'COMIDA BAJA EN SODIO PARA PACIENTES CON HIPERTENSIÓN', 80.00, 42.00, 0, 0, 'FLAT', NULL, NULL, true),
-- Extras
('SUPLEMENTO NUTRICIONAL', 'BEBIDA DE SUPLEMENTO NUTRICIONAL TIPO ENSURE O SIMILAR', 45.00, 28.00, 20, 5, 'FLAT', NULL, NULL, true),
('PORCIÓN DE FRUTA EXTRA', 'PORCIÓN ADICIONAL DE FRUTA FRESCA DE TEMPORADA', 15.00, 8.00, 0, 0, 'FLAT', NULL, NULL, true),
('BEBIDA CALIENTE EXTRA', 'CAFÉ, TÉ O CHOCOLATE CALIENTE ADICIONAL', 10.00, 5.00, 0, 0, 'FLAT', NULL, NULL, true),
('JUGO NATURAL EXTRA', 'VASO DE JUGO NATURAL DE NARANJA O FRUTA DE TEMPORADA', 15.00, 8.00, 0, 0, 'FLAT', NULL, NULL, true)
) AS v(name, description, price, cost, quantity, restock_level, pricing_type, time_unit, time_interval, active)
WHERE c.name = 'Alimentación'